[serve]
# The address to serve on LAN.
address = "127.0.0.1"
# The address to serve on WAN.
# address = "0.0.0.0"
# The port to serve on.
port = 8000
open=true

[build]
dist = "dist"
minify = "always"
hash = "true"
public_url = "/"
release = false

[watch]
folder = ["assets/*"] 
